### ISSUE TITLE
installation on centos

### ISSUE THREAD

**Issue by pontikos** [openeyes/OpenEyes#176]
Hello, I'm in the process of trying to get OpenEyes up and running on a CentOS 7 machine.  What is the easiest way to do the installation?  Do you have an image I can download?

**Comment by bizmate** [comment]
Have you tried 'vagrant up' ?

**Comment by antonypenn** [comment]
Hi,
There is a new set of installation scripts available. Please note that the system is only intended/tested for running under ubuntu, so you may need to adapt the scripts.

Check out the oe_installer repo. It contains new scripts for building a machine. The first step is to create a vagrant-based box, which you will skip. Follow the commands in install-system.sh and install-oe.sh, these will show you the steps needed. You will need to edit certain commands for CentOS (eg replace apt-get with rpm, etc)

**Comment by pontikos** [comment]
Thanks for the prompt replies, I have made some progress and since I have a virtual box setup which runs http and mysqld I have followed the instructions at http://github.com/openeyes/OpenEyes/wiki/Quick-Start and put openeyes under /var/www/html

I have also created the mysql database.

Now I'm getting the following error:
```
2015/11/10 13:31:21 [error] [exception.CDbException] could not find driver
2015/11/10 13:31:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /var/www/html/openeyes/vendor/yiisoft/yii/framework/db/CDbConnection.php:388
Stack trace:
#0 /var/www/html/openeyes/vendor/yiisoft/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/openeyes/vendor/yiisoft/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/openeyes/vendor/yiisoft/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CDbHttpSession.php(175): CModule->getComponent('db')
#4 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CDbHttpSession.php(221): CDbHttpSession->getDbConnection()
#5 [internal function]: CDbHttpSession->readSession('drgak58dik1qpfd...')
#6 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CHttpSession.php(114): session_start()
#7 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CHttpSession.php(88): CHttpSession->open()
#8 /var/www/html/openeyes/vendor/yiisoft/yii/framework/base/CModule.php(387): CHttpSession->init()
#9 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CWebApplication.php(201): CModule->getComponent('session')
#10 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/auth/CWebUser.php(199): CWebApplication->getSession()
#11 /var/www/html/openeyes/vendor/yiisoft/yii/framework/base/CModule.php(387): CWebUser->init()
#12 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CWebApplication.php(209): CModule->getComponent('user')
#13 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/auth/CAccessControlFilter.php(132): CWebApplication->getUser()
#14 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#15 /var/www/html/openeyes/protected/controllers/BaseController.php(47): CFilter->filter(Object(CFilterChain))
#16 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): BaseController->filterAccessControl(Object(CFilterChain))
#17 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('index')
#21 /var/www/html/openeyes/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#22 /var/www/html/openeyes/vendor/yiisoft/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#23 /var/www/html/openeyes/index.php(45): CApplication->run()
#24 {main}
REQUEST_URI=/openeyes/
---
2015/11/10 13:31:21 [error] [exception.CDbException] could not find driver
2015/11/10 13:31:21 [error] [exception.CDbException] could not find driver
```

I suspect I might need to edit the `openeyes/protected/config/console.php` file?


@bizmate I have tried vagrant on another machine running OS X capitan but get an error:
```
fatal error: runtime: bsdthread_register error (unset DYLD_INSERT_LIBRARIES)

runtime stack:
runtime.throw(0x1943d5)
	/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:491 +0xad fp=0x7fff5fbff380 sp=0x7fff5fbff350
runtime.goenvs()
	/Users/mitchellh/code/3rdparty/go/src/runtime/os_darwin.c:103 +0x60 fp=0x7fff5fbff398 sp=0x7fff5fbff380
runtime.schedinit()
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbff3c0 sp=0x7fff5fbff398
runtime.rt0_go(0x7fff5fbff3f8, 0x2, 0x7fff5fbff3f8, 0x0, 0x0, 0x2, 0x7fff5fbff5a0, 0x7fff5fbff5a8, 0x0, 0x7fff5fbff5ab, ...)
	/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbff3c8 sp=0x7fff5fbff3c0
```

@antonypenn thanks I had also tried the Cookbook approach but haven't been successful in getting that working, however as I said above I think if I can fix the db connection error I should be able to get it working!

**Comment by pontikos** [comment]
I've tried Vagrant and can't get it to work:
```
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (3.10.0-229.14.1.el7.x86_64) or it failed to
         load. Please recompile the kernel module and install it by
```

I noticed your demo server is also down http://demo.openeyes.org.uk/

**Comment by bizmate** [comment]
The virtual box error you are showing is due to the fact that you might need to "recompile the kernel module and install it ..." This is an operation you need to do to make sure Virtualbox is working correctly and more often than not it happens when you upgrade Virtualbox.

i.e.

run vboxmanage -v

This should show the same error message. Just follow the instructions in this error to recompile the kernel module.

**Comment by antonypenn** [comment]
Also note that for virtualbox, you need version 4.3 and NOT version 5, as there is a problem with shared folders in versions after 4.3.

**Comment by antonypenn** [comment]
@pontikos  have you resolved your issues now?

**Comment by pontikos** [comment]
No I haven't unfortunately and I've given up for now.

**Comment by antonypenn** [comment]
Ok, I will close this ticket off for now. The new installation routine should be fully deployed to the master branch and all documentation updated in the next week or so, so check back when you are ready to try again.
