### ISSUE TITLE
Dead patient trigger migration error

### ISSUE THREAD

**Issue by splatEric** [openeyes/OpenEyes#395]
Error upgrading from 1.12 to 1.15

```
> execute SQL: DROP TRIGGER cancel_dead_patient_bookings ...exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1360 Trigger does not exist. The SQL statement executed was: DROP TRIGGER cancel_dead_patient_bookings' in /var/www/html/openeyes/protected/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/html/openeyes/protected/yii/framework/db/CDbMigration.php(164): CDbCommand->execute(Array)
#1 /var/www/html/openeyes/protected/migrations/m160615_093409_patient_dead_trigger_update.php(7): CDbMigration->execute('DROP TRIGGER ca...')
#2 /var/www/html/openeyes/protected/yii/framework/cli/commands/MigrateCommand.php(385): m160615_093409_patient_dead_trigger_update->up()
#3 /var/www/html/openeyes/protected/yii/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m160615_093409_...')
```

**Comment by splatEric** [comment]
This issue has arisen because a migration has been created in core for something that is only created in operation booking. The migration needs to be moved and more defensive.
