### ISSUE TITLE
"Installing for live use" issue

### ISSUE THREAD

**Issue by PaoloVIP** [openeyes/OpenEyes#932]
Tested on Ubuntu 14.04 LTS minimal installation. Normal user, with sudo privileges.
ProxMox LXC Container 1GbRam

**Step 1**: oe_installer repository to your home directory. Run: **git clone https://github.com/openeyes/oe_installer.git**
Ok, no errors

**Step 2**: **sudo oe_installer/install/install-system.sh**
Ok, no errors. Only removed fallocate, 'cause my system doesn't support it

**Step 3**: **sudo oe_installer/install/install-oe.sh --live**
openeyes -> ok, no errors
eyedraw -> ok, no errors

**Here starts some issues:**

```
IOLMasterImport: Doesn't currently exist - cloning: Cloning into 'IOLMasterImport'...
remote: Counting objects: 1313, done.
remote: Total 1313 (delta 0), reused 0 (delta 0), pack-reused 1313
Receiving objects: 100% (1313/1313), 32.46 MiB | 157.00 KiB/s, done.
Resolving deltas: 100% (755/755), done.
Checking connectivity... done.

uzipping yii. Please wait...
.
unzip:  cannot find or open vendors.zip, vendors.zip.zip or vendors.zip.ZIP.
.
unzip:  cannot find or open vendors.zip, vendors.zip.zip or vendors.zip.ZIP.
*********** WARNING: Restoring backed up local configuration ... ***********
Installing/updating composer dependencies for LIVE
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 7 installs, 0 updates, 0 removals
  - Installing symfony/options-resolver (v3.2.6): Loading from cache
  - Installing endroid/qrcode (1.9.1): Loading from cache
  - Installing rlanvin/php-rrule (v1.2.0): Loading from cache
  - Installing setasign/fpdi (1.6.1): Loading from cache
  - Installing setasign/fpdf (1.8.1): Loading from cache
  - Installing setasign/fpdi-fpdf (1.6.1): Loading from cache
  - Installing yiisoft/yii (1.1.14): Loading from cache
Generating autoload files
Installing/updating npm dependencies for LIVE

  Compiling IOLMAsterImport. Please wait....

  

Migrating database...
Migrations applied - see /etc/openeyes/migrate.log for more details

Clearing caches...

(re)building assets...

...Done

Performing database migrations

Yii Migration Tool v1.0 (based on Yii v1.1.14)

Total 65 new migrations to be applied:
    m160217_103151_nod_export
    m160217_115954_add_setting_manual_biometry_off
    m160310_121034_link_medication_and_prescription
    m160311_105813_NOD_export_RBAC
    m160318_132703_new_doctor_grades
    m160420_120232_add_indexes_to_NOD_tables
    m160421_131246_add_indexes_to_HSCIC_tables
    m160425_095432_create_patient_merge_request_table
    m160426_105008_add_deleted_flag_to_patient
    m160426_222411_unique_codes
    m160503_142416_initial_worklist_models
    m160504_102700_unique_code_mapping
    m160510_075145_add_automatic_worklists
    m160511_095327_patient_shortcode
    m160517_083543_automated_event
    m160517_085926_add_media_storage_tables
    m160517_103422_add_patient_merge_RBAC_rules
    m160519_105335_add_new_risks
    m160520_144440_add_deleted_flag_patient_merge_request
    m160525_092545_user
    m160603_140012_display_institution_name
    m160606_150502_city_satellite_settings
    m160610_130617_nhs_num_verification
    m160614_085916_patient_is_deceased_flag
    m160615_093409_patient_dead_trigger_update
    m160622_094034_alter_settings_value_size
    m160711_125908_unique_columns_unique_code_mapping
    m160714_084347_constrain_worklist_attributes
    m160819_171457_add_user_signature
    m160823_100518_add_user_id_to_unique_codes_mapping
    m160831_133149_doctor_risk_grades
    m160909_100958_update_medical_retinal
    m160915_093448_add_document_management_tables
    m160928_073106_drop_medication_frequency_foreign_key
    m161006_104513_support_hours
    m161021_102624_genetic_patient_relations
    m161026_135722_remove_patient_merge_unique_audit_action
    m161112_115907_move_ToCc_from_doc_output_to_target
    m161210_150415_add_correspondence_banner_settings
    m161219_195513_add_user_is_technician_field
    m161222_161414_docman_log
    m170110_152227_remove_migration_route_fk
    m170118_145106_remove_is_tech
    m170124_151953_update_shortcodes
    m170126_161056_docmandb_changes
    m170126_164355_add_is_local_flag_to_patient
    m170127_102601_add_patient_create_role
    m170202_203916_add_noncontact_tonometer_to_iop
    m170204_085121_add_visibility_field_to_iop
    m170204_085917_add_iot_webstar_other
    m170222_132650_add_new_fields_to_drug_set_item
    m170228_103424_add_6days_drug_duration
    m170228_122555_remove_route_option_id_from_drug_set_item_table
    m170305_142449_create_keratoconus
    m170305_160630_add_keratoconus_data
    m170307_191643_add_enable_prescriptions_sys_setting
    m170308_180514_create_prescription_edit_reasons_table
    m170310_114213_add_new_system_setting
    m170313_104815_change_snr_column_default_in_et_ophinbiometry_measurement
    m170314_104129_add_new_system_setting_require_exam_before_booking
    m170315_134817_add_national_code_to_drugs_table
    m170317_132408_add_items_to_audit_action
    m170321_183126_predicted_refraction_nullable_in_element_ophtroperationnote_cataract
    m170331_085338_change_contact_table_collation
    m170516_101300_CXL_dataset_RBAC

*** applying m160217_103151_nod_export
    > add column pupil_size VARCHAR(10) to table et_ophtroperationnote_cataract ...exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'openeyes.et_ophtroperationnote_cataract' doesn't exist. The SQL statement executed was: ALTER TABLE `et_ophtroperationnote_cataract` ADD `pupil_size` VARCHAR(10)' in /var/www/openeyes/protected/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/openeyes/protected/yii/framework/db/CDbCommand.php(1377): CDbCommand->execute()
#1 /var/www/openeyes/protected/yii/framework/db/CDbMigration.php(286): CDbCommand->addColumn('et_ophtroperati...', 'pupil_size', 'VARCHAR(10)')
#2 /var/www/openeyes/protected/migrations/m160217_103151_nod_export.php(7): CDbMigration->addColumn('et_ophtroperati...', 'pupil_size', 'VARCHAR(10)')
#3 /var/www/openeyes/protected/yii/framework/cli/commands/MigrateCommand.php(385): m160217_103151_nod_export->up()
#4 /var/www/openeyes/protected/yii/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m160217_103151_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /var/www/openeyes/protected/yii/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(OEMigrateCommand), Array)
#7 /var/www/openeyes/protected/yii/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#8 /var/www/openeyes/protected/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#9 /var/www/openeyes/protected/yii/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#10 /var/www/openeyes/protected/yii/framework/yiic.php(33): CApplication->run()
#11 /var/www/openeyes/protected/yiic.php(27): require_once('/var/www/openey...')
#12 /var/www/openeyes/protected/yiic(4): require_once('/var/www/openey...')
```
Can you drive me in the right direction, please?

**Comment by PaoloVIP** [comment]
Ok, I got it, with some changes. This was installed on a clean Lxc Ubuntu Server 14.04 Lts, using ProxMox. Intended for live use.

First php5.6 is required:
```
sudo apt-get install software-properties-common python-software-properties
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
sudo add-apt-repository ppa:ondrej/php
```

--

In oe_installer/install/install-system.sh disable set up swap space removing "!" from
```
# SET UP SWAP SPACE
if [ ! "$dependonly" = "1" ]; then
```
so it became:
```
`if [ "$dependonly" = "1" ]; then`
```

Add sudo to debconf-set-selections
```
sudo debconf-set-selections <<< 'mariadb-server-5.5 mysql-server/root_password password password'
sudo debconf-set-selections <<< 'mariadb-server-5.5 mysql-server/root_password_again password password'
```

Live to apt install only mariadb-server
```
apt install -y mariadb-server
```

---

Install prerequisites (mysql-server will be installed from install-system.sh)
```
apt install -y git-core libapache2-mod-php5.6 php5.6-cli php5.6-mysql php5.6-ldap php5.6-curl php5.6-xsl php5.6-gd imagemagick php5.6-imagick libjpeg62 mariadb-client debconf-utils unzip xfonts-75dpi default-jre libgamin0 gamin openjdk-7-jdk xfonts-base ruby ant libbatik-java libreoffice-core libreoffice-common libreoffice-writer php5.6-mcrypt php5.6-common php5.6-json curl npm
```

Create the following directories:
```
sudo mkdir /etc/php5
sudo mkdir /etc/php5/apache2
sudo mkdir /etc/php5/cli
sudo mkdir /usr/lib/php5
sudo mkdir /usr/lib/php5/20121212
```

Create the following symlink:
```
sudo ln -s /etc/php/5.6/apache2/php.ini /etc/php5/apache2/php.ini
sudo ln -s /etc/php/5.6/cli/php.ini /etc/php5/cli/php.ini
```

At this point run
```
sudo oe_installer/install/install-system.sh
```

---

In oe_installer/install/install-oe.sh change 
```
if [ ! "$live" = "1" ]; then
    echo ""
        echo "Creating blank database..."
```
to
```
if [ "$live" = "1" ]; then
    echo ""
        echo "Creating blank database..."
```

At this point run
```
sudo oe_installer/install/install-oe.sh --live
```

---

Change /etc/apache2/sites-available/000-default.conf to something like this:
```
<VirtualHost *:80>
        ServerName yourhost.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/openeyes

        <Directory /var/www/openeyes>
                Options FollowSymLinks
                AllowOverride All
                Order allow,deny
                Allow from all
        </Directory>

        LogLevel info

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

---

Go to yourhost.com and login with admin, pwd admin.

**Comment by biskyt** [comment]
Thank you. The PHP 5.6 dependency will be resolved in the next major release, as will some of the installer issues you have mentioned. I will have a look through your fixes in more detail over the coming weeks and update the installer, etc, where appropriate
